version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    depends_on:
      - db
    environment:
      - 'spring.datasource.url=jdbc:postgresql://db:5432/usecasejoueursDB'

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usecasejoueursDB

